export enum estudiosKeyTranslate {
    ENTIDADUPN = 'ESTUDIOS.ENTIDAD.UPN',

    TITLE = 'ESTUDIOS.TITLE',
    SUBTITULO = 'ESTUDIOS.SUBTITLE',

    MAESTRIATITULO = 'ESTUDIOS.MAESTRIA.TITULO',
    MAESTRIAPERIODO = 'ESTUDIOS.MAESTRIA.PERIODO',
    MAESTRIASKILLS = 'ESTUDIOS.MAESTRIA.SKILLS',

    DIPLOMADOTITULO = 'ESTUDIOS.DIPLOMADO.TITULO',
    DIPLOMADOPERIODO = 'ESTUDIOS.DIPLOMADO.PERIODO',
    DIPLOMADOSKILLS = 'ESTUDIOS.DIPLOMADO.SKILLS',

    BACHILLERTITULO = 'ESTUDIOS.BACHILLER.TITULO',
    BACHILLERPERIODO = 'ESTUDIOS.BACHILLER.PERIODO',
    BACHILLERSKILLS = 'ESTUDIOS.BACHILLER.SKILLS',
}
