export enum experienciaKeyTranslate {
    TITULO1 = 'EXPERIENCIA.TITULO1',
    TITULO2 = 'EXPERIENCIA.TITULO2',

    ENTIDADINDECI = 'EXPERIENCIA.ENTIDAD.INDECI',
    PERIODOINDECI = 'EXPERIENCIA.PERIODO.INDECI',
    PUESTOINDECI = 'EXPERIENCIA.PUESTO.INDECI',
    BREVEINDECI = 'EXPERIENCIA.BREVE.INDECI',
    TAREASINDECI = 'EXPERIENCIA.TAREAS.INDECI',

    PERIODOPOLYSOFT = 'EXPERIENCIA.PERIODO.POLYSOFT',
    PUESTOPOLYSFOT = 'EXPERIENCIA.PUESTO.POLYSOFT',
    BREVEPOLYSFOT = 'EXPERIENCIA.BREVE.POLYSOFT',
    TAREASPOLYSOFT = 'EXPERIENCIA.TAREAS.POLYSOFT',

    ENTIDADPLATANITOS = 'EXPERIENCIA.ENTIDAD.PLATANITOS',
    PERIODOPLATANITOS = 'EXPERIENCIA.PERIODO.PLATANITOS',
    BREVEPLATANITOS = 'EXPERIENCIA.BREVE.PLATANITOS',
    TAREASPLATANITOS = 'EXPERIENCIA.TAREAS.PLATANITOS',

    ENTIDADFC = 'EXPERIENCIA.ENTIDAD.FC',
    PERIODOFC = 'EXPERIENCIA.PERIODO.FC',
    BREVEFC = 'EXPERIENCIA.BREVE.FC',
    TAREASFC = 'EXPERIENCIA.TAREAS.FC',

    PERIODOALIGNET = 'EXPERIENCIA.PERIODO.ALIGNET',
    BREVEALIGNET = 'EXPERIENCIA.BREVE.ALIGNET',
    TAREASALIGNET = 'EXPERIENCIA.TAREAS.ALIGNET',

    ENTIDADFOTOLATINO = 'EXPERIENCIA.ENTIDAD.FOTOLATINO',
    PERIODOFOTOLATINO = 'EXPERIENCIA.PERIODO.FOTOLATINO',
    BREVEFOTOLATINO = 'EXPERIENCIA.BREVE.FOTOLATINO',
    TAREASFOTOLATINO = 'EXPERIENCIA.TAREAS.FOTOLATINO',
}
