export enum genericosKeyTranslate {
    INFORMACION = 'GENERICOS.INFORMACION',
    VERMAS = 'GENERICOS.VERMAS',
    COMPETENCIASTECNICAS = 'GENERICOS.COMPETENCIA.TECNICA',
    PROYECTOS = 'GENERICOS.PROYECTOS',

    FULLSTACK = 'GENERICOS.FULLSTACK',
    FRONTEND = 'GENERICOS.FRONTEND',
    BACKEND = 'GENERICOS.BACKEND',

    BASICOS = 'GENERICOS.BASICOS',
    LENGUAJES = 'GENERICOS.LENGUAJES',
    HERRAMIENTAS = 'GENERICOS.HERRAMIENTAS',
    BD = 'GENERICOS.BD',
    GEO = 'GENERICOS.GEO',
    METODOLOGIAS = 'GENERICOS.METODOLOGIAS',
    VERSIONABLE = 'GENERICOS.VERSIONALE',
}
