export enum headerKeysTranslate {
    INICIO = 'HEADER.INICIO',
    ACERCADEMI = 'HEADER.ACERCADEMI',
    PROYECTOS = 'HEADER.PROYECTOS',
    CONOCIMIENTOS = 'HEADER.CONOCIMIENTOS',
    EXPERIENCIAS = 'HEADER.EXPERIENCIAS',
    EDUCACION = 'HEADER.EDUCACION',
}
