export enum proyectosKeyTranslate {
    TITULO = 'PROYECTOS.TITULO',
    SUBTITULO = 'PROYECTOS.SUBTITULO',
    TITULOMODAL = 'PROYECTOS.TITULO.MODAL',

    INDECI = 'PROYECTOS.ENTIDAD.INDECI',
    CORTASINPAD = 'PROYECTOS.CORTA.SINPAD',
    DESCRIPCIONSINPAD = 'PROYECTOS.DESCRIPCION.SINPAD',

    CORTAEVANOZ = 'PROYECTOS.CORTA.EVANOZ',
    DESCRIPCIONEVANOZ = 'PROYECTOS.DESCRIPCION.EVANOZ',

    CORTATUTATI = 'PROYECTOS.CORTA.TUTATI',
    DESCRIPCIONTUTATI = 'PROYECTOS.DESCRIPCION.TUTATI',

    CORTACUENTASCLARAS = 'PROYECTOS.CORTA.CUENTASCLARAS',
    DESCRIPCIONCUENTASCLARAS = 'PROYECTOS.DESCRIPCION.CUENTASCLARAS',

    CORTACRYPTO = 'PROYECTOS.CORTA.CRYPTO',
    DESCRIPCIONCRYPTO = 'PROYECTOS.DESCRIPCION.CRYPTO',

    TITULOWAYLESS = 'PROYECTOS.TITULO.WAYLESS',
    CORTAWAYLESS = 'PROYECTOS.CORTA.WAYLESS',
    DESCRIPCIONWAYLESS = 'PROYECTOS.DESCRIPCION.WAYLESS',
}
