export enum quiensoyKeyTranslate {
    HOLA = 'QUIENSOY.HOLA',
    DEVELOPER1 = 'QUIENSOY.DEVELOPER1',
    DEVELOPER2 = 'QUIENSOY.DEVELOPER2',
    DESCRIPCION = 'QUIENSOY.DESCRIPCION',
    PORTAFOLIO = 'QUIENSOY.PORTAFOLIO',
}
